WIP: Fix process/thread extraction on v6.7+
Since kernel commit 8e1f385104ac ("kill task_struct->thread_group")
removed thread_group, the current code no longer works and throws the
following error:
Python Exception <class 'gdb.error'>: There is no member named thread_group.

Switched to iterate using task["signal"]["thread_head"] instead, similar
to the fix in 854f2764b577 ("scripts/gdb/tasks: fix lx-ps command error Beta")

TODO:
- Test if this works on older kernels too, if not, add some logic
  that will automatically work with all kernel versions.
- Also investigate relation to ptesarik/kdump-gdbserver#1